[versions]
kotlin = "1.9.25"
spring-boot = "3.4.3"
spring-dependency-management = "1.1.7"
gralvm-native = "0.10.3"
spring-cloud = "2024.0.0"
spring-modulith = "1.3.3"

[libraries]
kotlin-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect"}

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" } #plugin-spring = { id = "plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "gralvm-native" }